version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: "sqlite:latest"
    volumes:
      - sqlite_data:/var/lib/sqlite

volumes:
  redis_data:
  sqlite_data: 